apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{name}}
  labels:
    app: {{app}}
spec:
  replicas: {{amount}}
  selector:
    matchLabels:
      app: {{app}}
  template:
    metadata:
      labels:
        app: {{app}}
    spec:
      containers:
      - name: {{app}}
        image: {{image}}
        ports:
        - containerPort: {{port}}
      imagePullSecrets:
      - name: regcred