apiVersion: v1
kind: Service
metadata:
  name: {{service-name}}
spec:
  type: LoadBalancer
  selector:
    app: {{app}}
  ports:
    - protocol: TCP
      port: {{port}}
      targetPort: {{port}}
      nodePort: {{external-port}}