apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{name}}
  labels:
    app: {{app}}
spec:
  replicas: {{amount}}
  selector:
    matchLabels:
      app: {{app}}
  template:
    metadata:
      labels:
        app: {{app}}
    spec:
      containers:
      - name: {{name}}
        image: {{image}}
        ports:
        - containerPort: {{port}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{service-name}}
spec:
  selector:
    app: {{name}}
  ports:
    - protocol: TCP
      port: {{port}}
      targetPort: {{port}}
